  
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: |
          yarn install
          yarn export

      - name: Deploy to main repo
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '__sapper__/export'
          destination-github-username: 'johannchopin'
          destination-repository-name: 'restapify'
          target-branch: 'website'
          user-email: johannchopin@pm.me
          commit-message: '🚀 Deploy website'
